### ISSUE TITLE
Discussion: Include more controls and API into v1

### ISSUE THREAD

**Issue by vbcodec** [Microsoft/xaml-standard#61] opened 2017-05-12 13:22 UTC
In UWP there are 70 controls, most of them pretty universal that should go to into standard, But more important is to stanandardise API than just XAML schema.. API is defined by classes and behaviour. With standarized API, anyone can write libraries with UI code that can run on every platform. 
Putting XAML alone into standard is way too low.

**Comment by skendrot** [comment] 2017-05-16 15:24
Possible duplicate of #58 
Also see earlier issues asking for specific controls to be part of standard

**Comment by insinfo** [comment] 2017-05-21 05:46
@vbcodec 
I agree with you, the standard has to be robust and well complete, but I think that every control that goes into Standard has to be discussed in detail in its specification, ie its properties, nameclatura, syntax and so on.

**Comment by harinikmsft** [comment] 2017-05-26 21:54
We hear you. We are starting v1 with the idea of a meaningful modern subset that can target maximum different end points. Like .NET Standard, XAML Standard will also grow and as future versions evolve, more and more controls and APIs will become a part of the standard. 

Since this seems to be a general topic without specific issues, I am closing it to keep the repo manageable. Please feel free to file specific controls that you would like to see if they are not captured in issues already.

**Closed by harinikmsft** 2017-05-26 21:54 UTC
