### ISSUE TITLE
Recommend: standardize DataContext and BindingContext

### ISSUE THREAD

**Issue by kmote00** [Microsoft/xaml-standard#150] opened 2017-05-22 13:21 UTC
I am happy to hear that [an effort to standardize Xamarin.Forms and Windows XAML](https://blogs.windows.com/buildingapps/2017/05/19/introducing-xaml-standard-net-standard-2-0/#rtcbWrDJ9KhXLo8D.97). I would like to suggest that DataContext and BindingContext should be considered for standardization as well. As discussed [here](https://stackoverflow.com/questions/44080106/whats-the-difference-between-datacontext-and-bindingcontext/44080304#44080304), the difference between these two terms is confusing. Can this be added to the list of syntax to be standardized?

**Comment by lthib** [comment] 2017-05-22 21:50
This was already accepted in #8

**Comment by harinikmsft** [comment] 2017-05-26 20:37
Duplicate of #8

**Closed by harinikmsft** 2017-05-26 20:37 UTC
Labels: duplicate
