### ISSUE TITLE
Add support to Padding

### ISSUE THREAD

**Issue by rodrigoratan** [Microsoft/xaml-standard#149] opened 2017-05-22 11:36 UTC
Margin is the outside 'space' (distance of parent margins) of a control, but padding is the inside space that is taken from the available space that is left to inner controls. true xaml parity should consider padding

**Comment by insinfo** [comment] 2017-05-22 23:28
@rodrigoratan
Gets or sets a Thickness value that describes the amount of space between a Border and its child element.
If I am not mistaken, WPF supports this, but not in the same order as CSS

```xaml
<Button MinWidth="75" Padding="left,top,right,bottom" Content="It speaks!" />
```
So for 2 left padding, 3 top, 4 right, and 5 bottom:
```xaml
<Button MinWidth="75" Padding="2,3,4,5" Content="It speaks!" />
```
	
Wouldn't it be nice if it had the same order as CSS?

**Comment by Odonno** [comment] 2017-05-23 10:38
I rather prefer the way WPF/UWP handle Padding.

**Comment by birbilis** [comment] 2017-05-23 10:38
Such quadruplets are in other properties too I guess (say margin), so would need to do this everywhere, plus would just confuse people from WPF/Silverlight

**Comment by dotMorten** [comment] 2017-05-23 15:50
> Wouldn't it be nice if it had the same order as CSS?

Wouldn't it be nice if every single existing XAML app out there didn't break because they suddenly changed the order?
This is a breaking change proposal that has no value add, and as such I could not disagree more.

**Comment by dotMorten** [comment] 2017-05-23 15:52
This is a duplicate of #11

**Comment by BillHenning** [comment] 2017-05-23 16:26
XAML has one way of doing it and CSS has another.  While it would have been nice if they were originally in sync, at this stage, I'd prefer that XAML stay as is and not break everything in XAML that has been created in the past.

**Comment by rodrigoratan** [comment] 2017-05-23 17:55
@dotMorten you're right, I searched for 'padding' and didn't find #11 , thanks for the heads up

**Closed** 2017-05-23 17:56 UTC

**Comment by insinfo** [comment] 2017-05-23 19:18
I did not want to say that "WPF Padding" has to be equal to "CSS Padding", more that would be nice if it were. But now I think it's too late for that.
