### ISSUE TITLE
Add Controls Deferred Loading

### ISSUE THREAD

**Issue by francedot** [Microsoft/xaml-standard#37] opened 2017-05-11 17:19 UTC
## Deferred Loading
Port Deferred Loading Strategy of UWP to Xamarin.Forms.

```xml
<Grid x:DeferLoadStrategy="Lazy"/>
```

**Comment by bschoepke** [comment] 2017-05-11 17:36
Dupe of #22

x:Load is the replacement for x:DeferLoadStrategy and adds support for unloading

**Comment by francedot** [comment] 2017-05-11 17:41
@bschoepke Good to know. I didn't catch that API update..

**Comment by harinikmsft** [comment] 2017-05-26 21:23
Dupe of #22

**Closed by harinikmsft** 2017-05-26 21:23 UTC
Labels: duplicate
