### ISSUE TITLE
Please HIGHLY consider to include WPF in the XAML Standard as well!

### ISSUE THREAD

**Issue by daneshmandi** [Microsoft/xaml-standard#42] opened 2017-05-11 18:42 UTC
I am one of the early XAML adapters and passionate who started using XAML in WPF, Silverlight, UWP and Xamarin Forms since **Avalon** release (yeah Avalon you know what I mean) .  

As a developer who spents most of his 11 years of dev experience with XAML, I am asking to please **HIGHLY** consider including **WPF for XAML Standard** as well. I know you may say UWP is good enough but you are wrong. **REAL world** demanding more **WPF** apps than UWP. I know MS wants to force devs to use UWP instead but believe me this will never work. Lets dev decide using the right tool for the right job. If you think I am saying this because I don't like UWP, you are wrong, as I have done a couple of [UWP apps](http://PortraitPad.com), too. But WPF is still very useful and practical for so many enterprise level projects.

Microsoft has hurt .Net devs so many times with its shifting dev strategies quite often (Silverlight and Windows Phone as examples). But **.Net Standards** and now **XAML Standards** are very good approaches and actions. So please **HEAR** dev feedback and respect and include them.

I am not talking about complex WPF Controls, I am talking about the WPF XAML basics. (Panels, Binding, Templates and Styles, and so on.)

I am asking to consider this in the **V1**. This is **SO** important to us.

**Comment by dotMorten** [comment] 2017-05-11 18:44
Duplicate of #20

**Comment by Micro666** [comment] 2017-05-11 22:00
No don't include the WPF flavour of XAML in the XAML Standard. The main reason being that UWP / Xamarin are now the future.

Whilst I myself am a WPF developer, I am also a UWP developer. WPF is legacy, but that being said, I'd be happy for some elements of WPF XAML to make it in e.g. DelayBindings, Triggers (Trigger, MultiTrigger, DataTrigger) etc.

**Comment by Mike-EEE** [comment] 2017-05-11 23:07
Unfortunately, UWP's Xaml model lacks important concepts such as markup extensions.  And even the markup extensions they are planning are a watered-down (if not dumbed-down) version of what WPF (and even Xamarin.Forms, or really any other Xaml model outside of UWP's) offers.  WPF is the big daddy.  Even if it is a little aged, more .NET developers are still in favor of its flavor (LOL) than UWP's by far.

That said, I am all in favor of improving upon WPF's model to define the new standard here. 😄

**Comment by ahoefling** [comment] 2017-05-12 02:24
There are some great controls in the WPF XAML implementation that should be in the XAML standard but taking everything from WPF would not be useful and create a lot of bloat in my opinion.

I've been going through picking and choosing some of my favorite controls from WPF that should be in the XAML standard and would be useful for Xamarin or UWP

**Comment by andyb1979** [comment] 2017-05-12 08:49
See my conversation in issue #27 about why MarkupExtension, x:Static, RelativeSource FindAncestor are important. 

I totally forgot about Triggers but yes these are really useful also. Without them we have to resort to loads of boilerplate code in Viewmodels or custom attached properties just to do a job which is super-easy in vanilla WPF. 

Part of the reason why UWP and Xamarin.Forms lacks the millions of WPF devs is because it just can't compete with the 11 year old technology.

**Comment by daneshmandi** [comment] 2017-05-12 23:48
#27 #20

**Comment by daneshmandi** [comment] 2017-05-12 23:49
#27

**Comment by jackbond** [comment] 2017-05-16 20:22
To make XAML-standard great, Microsoft should pretend that no other versions other than WPF exist. Silverlight was tolerable, but even that never got things like Multibinding or CollectionViewSource properly implemented. Furthermore, some of the decisions made by the UWP guys were HORRIFIC. For example, in WPF, things were fairly consistent, but in UWP were just random or plain stupid. For example, buttons dropped into a grid do not stretch, but are left aligned for no reason. Please do not repeat mistakes like that.

**Comment by GeraudFabien** [comment] 2017-05-18 18:09
> Duplicate of #20

It was not a duplicate at first because #20 is about taking WPF as a base. This one is about porting WPF to.

> For example, buttons dropped into a grid do not stretch, but are left aligned for no reason. Please do not repeat mistakes like that.

I hope you kidding because there plenty of advantage of UWP and the only drawback you find is that. I'm the only one to find funny how bad you want WPF be better thant UWP. I never even remark this difference (And as far i know it have nothinks to do with XAML. It's a designer problem). 
Evry developper prefer the techno they start in because they master it. But XAML will be dead if we only take WPF.

**Comment by andyb1979** [comment] 2017-05-18 18:13
Uhm, UWP is missing loads of features which still only exist in WPF.

See issue #27 for a list (not exhaustive)

**Comment by jackbond** [comment] 2017-05-18 18:35
@GeraudFabien 

"I hope you kidding because there plenty of advantage of UWP and the only drawback you find is that."

That's the tip of the iceberg. For example, can I use a CollectionViewSource to filter a Collection? No? Is it technically impossible or is Microsoft strapped for cash? Guess I'll just wait for the next version. Can I easily display a set of data in a clean grid, perhaps with a DataGrid control? Yes, but you have to use a third party control which only recently became free. So Microsoft is strapped for cash or did they simply not realize that a Datagrid is a FUNDAMENTAL CONTROL? Guess I'll just wait for the next version. I apologize if these seem like nitpicks, but Microsoft set the bar so high with WPF and Silverlight, that the early releases of UWP were a joke in comparison, and continue to disappoint. I've got several Silverlight apps which I could have ported to UWP by now, but Microsoft's FLAT OUT LIES to the Silverlight community pissed off a lot of people, and they never took any significant trouble to make amends.

**Comment by dotMorten** [comment] 2017-05-18 18:48
> It was not a duplicate at first because #20 is about taking WPF as a base. This one is about porting WPF to.

Compare the two titles:
 - Please HIGHLY consider to include WPF in the XAML Standard as well!
- Include WPF in the standard

How is that not a duplicate?

Further down the thread, I do offer up a compromise, since keeping WPF up to date with future versions of XAML Standard might not be on the drawing board. But it's original intent is the exact same as this issue - I'm just trying to be a little flexible and acknowledge the different challenges there are, rather than a take it or leave it attitude.

**Comment by Mike-EEE** [comment] 2017-05-22 12:07
While I have it in my clipboard. 😄 

Nice little breakdown of all known desktop OS's.  That Windows 7, tho (that means WPF and **NOT** UWP/XF):

http://www.netmarketshare.com/report.aspx?qprid=10&qptimeframe=M&qpsp=219&qpch=350&qpmr=24&qpdt=1&qpct=3&qpcustomd=0&qpcid=fw1328461&qpf=1

**Comment by harinikmsft** [comment] 2017-05-25 17:35
Agree with @dotMorten. Seems like a dupe of #20. Can we continue this conversation on that thread please?

**Closed by harinikmsft** 2017-05-25 17:35 UTC
Labels: duplicate

**Comment by neilcarberry** [comment] 2017-06-20 14:45
@GeraudFabien 
Seriously, How can you love UWP to much over WPF. I recently went into Blend for UWP and all i wanted to do was place some controls in a semi circle like in WPF along a path.... good fucking luck with that!

**Comment by crutkas** [comment] 2017-06-20 16:13
@neilcarberry please watch the language.

If you have issues with tooling or asks for UWP, please tell us over at https://wpdev.uservoice.com.  This is not the appropriate spot as it is only for XAML Standard
