### ISSUE TITLE
Please take in your consideration "FlowDirection" property 

### ISSUE THREAD

**Issue by abdelrazekbadr** [Microsoft/xaml-standard#194] opened 2017-06-17 11:47 UTC
This property can be set to one of two enumeration values, **LeftToRight** or **RightToLeft**. 
This property very important for application which have bidirectional content.
We propose that set this property in base object of controls, This will cause all of the controls contained within parent control  to respond appropriately to the  direction. If you are implementing custom controls, they should use FlowDirection to make appropriate layout changes for RTL and LTR languages.

Example of parent FlowDirection
```
<Page FlowDirection=”RightToLeft”>
    <Grid>
    <Grid.ColumnDefinitions>
      <ColumnDefinition Width=”0.5*” />
      <ColumnDefinition Width=”0.5*” />
    </Grid.ColumnDefinitions>
    <Button>Button</Button>
    <TextBlock Grid.Column=”1″> Hello </TextBlock>
  </Grid>
</Page>
```

Example of element FlowDirection
```
<TextBlock   FlowDirection="LeftToRight">
        This is a left-to-right TextBlock
</TextBlock>

```

```
<TextBlock  FlowDirection="RightToLeft">
        This is a right-to-left TextBlock
</TextBlock>

```

**Comment by birbilis** [comment] 2017-06-17 12:57
There is also some RTL semantics discussion here https://github.com/Microsoft/xaml-standard/issues/43

**Comment by danielkatz** [comment] 2017-06-17 20:41
It is a duplicate of #41

**Comment by crutkas** [comment] 2017-06-19 18:28
agreed, dup of #41

**Closed by crutkas** 2017-06-19 18:28 UTC
Labels: duplicate
