### ISSUE TITLE
Add TabItem control

### ISSUE THREAD

**Issue by Krzem0** [Microsoft/xaml-standard#67] opened 2017-05-12 17:36 UTC

**Comment by birbilis** [comment] 2017-05-16 09:23
maybe duplicate - there was another issue on Tabbed control

**Comment by skendrot** [comment] 2017-05-16 15:18
Duplicate of #30

**Closed** 2017-05-16 19:21 UTC

**Comment by mrlacey** [comment] 2017-05-20 18:38
please add the duplicate label :)

**Comment by Krzem0** [comment] 2017-05-21 09:37
I would, but I don't have this option. :|
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/
http://i65.tinypic.com/b5oetf.jpg

**Comment by Odonno** [comment] 2017-05-21 10:42
@mrlacey @Krzem0 Only moderators of this repository can apply labels.
